AllCops:
  Include:
  - 'Rakefile'
  - '*.gemspec'
  - 'lib/**/*.rb'
  - 'spec/**/*.rb'
  Exclude:
  - 'bin/**/*'
  - 'smoke/**/*'
  - 'Gemfile'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.2

Rails:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
  - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 120

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  Exclude:
  - "spec/**/*.rb"

Metrics/AbcSize:
  Max: 20
